apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: textext-app
  labels:
    # any Pods with matching labels are included in this Daemon Set
    app: kubernetes-series
    tier: monitor
spec:
  selector:
    # Pods will match with the following labels
    matchLabels:
      name: textext-app
  template:
    metadata:
      labels:
        name: textext-app
    spec:
      containers:
      - name: textext-app
        image: {{param.acr}}/microsoft/textext:latest
        ports:
        - containerPort: 80
        env:
        - name: WEBSITE_HOSTNAME
          value: "{{param.kubernetesHost}}"
        - name: AZURE_STORAGE_CONNECTION_STRING
          value: "{{param.storageConnectionString}}"
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          value: "{{param.appInsightsServiceKey}}"
        - name: AzureWebJobsStorage
          value: "{{param.techStorageConnString}}"
        - name: ContainerConnectionString
          value: "{{param.storageConnectionString}}"
        - name: ContainersList
          value: "{{param.StorageContainersAsString}}"
        - name: TikaContainerUrl
          value: "{{param.kubernetesGateway}}"
        - name: UserAgent
          value: "MicrosoftPOC/1.0"
        - name: X_Tika_PDFAllPagesAsImages
          value: "{{param.X_Tika_PDFAllPagesAsImages}}"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 4Gi
      nodeSelector:
        agentpool: poolskills

--- 
apiVersion: v1
kind: Service
metadata:
  name: textext-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    name: textext-app
